### PR TITLE
add main, fix some formatting and a little bit logic

### PR DESCRIPTION
**Pull request by rirze**
I thought the script could use some formatting fixes. I also made one or two logic improvements along the way. 

If there's anything I can explain with regards to my changes or any further things you would like to be improved (logic, algorithm, speed), let me know.

### CODE REVIEW

**Comment by jrthorstensen** [comment]
rirze -- Thanks!  But when you moved the line that defines "pixrange", you dropped the first argument (0) which broke the script.  I'm very new to github and am not sure just how to fix this, but if you fix it on your side it should work.

Also, I'm curious as to what advantages might flow from putting almost the whole thing in a
main.  There's so much argparsing going on that I don't see this as being used any other way without a major refactoring.

Is it also standard to never indent comment lines?  I've taken to indenting comment lines because it makes the flow of control easier to follow.

**Comment by rirze** [comment]
@jrthorstensen Thanks for catching the `arange(0...` -> `arange(...)`, I had a simple find-and-replace for something else and it did this change unintentionally. I will upload a commit with that fixed. Along that note, is there a test case I can use to verify the code logic? 

As for the question about `__main__`, the way you currently have your script will work fine as long as the script is used only as a standalone script. The 'Pythonic' way to do the equivalent thing, however, is to wrap the lines that you want to automatically execute when the file is called like a script into the '__main__' branch. This is preferable because it makes importing the file from another Python file much cleaner. For example, in your current version, if I wanted to import one the classes in `opextract.py` like `from opextract import aperature_params`, my simple Python import would fail because it would run the argparse lines and throw errors. This is because I cannot provide args while doing a regular Python import. 

I can see a way to provide the same functionality as a function for example. The arg parsing would stay in `__main__`, but the parsed parameters would be passed into a function that computes everything you currently have the outermost indent level of the script. This way, the logic is modularized to run at the script and module level without redundancy. Let me know if you want me to showcase this and you can decide from there if that is preferable.

I personally find indenting comment lines preferable, and I believe it is implicitly agreed to be the standard. The way you are doing them is perfectly fine.

**Comment by rirze** [comment]
Oh, also I'm not sure if you meant to close the Pull Request. My idea is that I can keep uploading changes with your feedback (which will automatically update here) until you reach a final decision of whether to merge or reject this pull request. 

If you would like to open the PR again, there should be a 'Reopen' button at the bottom of the page you could click.

**Comment by jrthorstensen** [comment]
Thanks again!  Your point on the re-usability of the other classes had escaped me, and I agree it's better to isolate the actual action in an if __name__ == "__main__"  block.  I certainly didn't mean to close the pull request -- I have done almost nothing on github. I'll reopen it now.

**Comment by jrthorstensen** [comment]
As for a test case to verify the logic,  I think maybe the safest thing is to run an end-to-end test using real data.  Do you think it would be worthwhile to upload some test data?

**Comment by rirze** [comment]
It would be worthwhile, as long as the expected output of the test data is uploaded as well.

**Comment by jrthorstensen** [comment]
I've uploaded a bit of test data!  Would you be able to test your version on it?

**Comment by rirze** [comment]
That's great! I was able to verify that the changes I made did not change the script output. 

I was able to separate the main chunk of code in this script into the `opextract` function, which takes in the host of parameters given by arg parse. In the future, if someone wanted to use this function in another Python script, they would be able to call `opextract(...)` with their custom parameters and also get output. 

I'll probably do a quick speed profile to see if there are any bottlenecks, and I'll proceed from there.

Let me know what you think!

**Comment by jrthorstensen** [comment]
This is looking good, though when I tried downloading and running I got an error that it couldn't find the function: 
~/Downloads/opextract-master/opextract.py kl115 -d -a 2 -r 15 > kl115.out
Traceback (most recent call last):
  File "/home/thorsten/Downloads/opextract-master/opextract.py", line 180, in <module>
    opextract(args.imroot, firstlinetoplot, lastlinetoplot, plot_sample, DISPAXIS, readnoise, gain, apmedfiltlength,
NameError: name 'opextract' is not defined

which seemed mysterious since it's right there in black and white.  Also, do you think it would be a good idea to make nearly all the adjustable parameters into keyword arguments with default values cribbed from the argparse?  It would seem rather painful to have to deal with that long string of positional arguments correctly.

**Comment by rirze** [comment]
Strange, that error is from when the `__main__` was above `def opextract()`. Moving `__main__` down after `def opextract()` fixes that problem. (The latest version of my fork fixes this, I suggest getting the latest commit)

As for the positional arguments concern, you can use keyword arguments for regular positional arguments. For example;
```python3
def test(a, b, c=2):
    print(a, b, c)

> test(0, 1, c=2) # works
> test(0, 1, 2) # also works
> test(a=0, b=1, c=2) # works as well
> test(a=0, 1, c=2) # doesn't work
> test(a=0, 1, 2) # also doesn't work
# the last two don't work because keyword arguments cannot follow positional arguments
# you'll get a 'SyntaxError: positional argument follows keyword argument' error
```

Hopefully, that satisfies your concern. 

Also, I've done a simple speed test and the current execution seems fine. It seems the greatest bottleneck is loading the files of the disk, which is not trivial to speed up.

If you have any further suggestions or comments, please let me know. Otherwise, I have no other ideas to implement.

**Comment by jrthorstensen** [comment]
Thanks for your help!   My point about the positional arguments was a different one, though, namely that it's nice to be able to call a function without specifying everything every time, especially in a context like this.  so 
```
def test(a, b, c = 1) :
    print(a, b, c)

test(1, 2)  # works
test(1)     # fails
```

In other words, you don't have default values to fall back on.

**Comment by jrthorstensen** [comment]
Hello again -- I just executed this pull request (I think -- believe it or not, this is the very first time I've done this).  I might tinker with the keyword argument thing, but that's very easy to do.  And thanks again!  This should make it quite a bit more useful.

**Comment by rirze** [comment]
Sounds good, I was preparing a global dictionary of default values that could be called upon in the arg parse parameter definitions and the `opextract()` default parameter list. Then there is only one place where defaults are declared (this does make default Python documentation a little muddy, but that's up to you). 

And congratulations! May it be the first of many...

**Pull request merged**
